language: node_js

node_js:
  - "8"

# Travis-CI Caching
cache:
  directories:
    - node_modules


# S: Build Lifecycle
install:
  - npm install

script:
  - npm run build

branches:
  only:
    - master